-- colors/colorscheme.lua

local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#E3E3E3", bg = "#1C1C1C"},
NormalNC = {link = "Normal"},
TabLineSel = {link = "Normal"},
Character = {fg = "#88AF88"},
PreProc = {link = "Character"},
SpecialChar = {link = "Character"},
SpecialComment = {link = "Character"},
ColorColumn = {bg = "#262626"},
Comment = {fg = "#AF8760"},
Conceal = {fg = "#FF0000"},
Conditional = {fg = "#D66000"},
Exception = {link = "Conditional"},
Keyword = {link = "Conditional"},
Label = {link = "Conditional"},
Repeat = {link = "Conditional"},
Constant = {fg = "#D66000"},
["@constant"] = {link = "Constant"},
CurSearch = {fg = "#262626", bg = "#FFD900", bold = true},
IncSearch = {link = "CurSearch"},
Search = {link = "CurSearch"},
Cursor = {reverse = true},
TermCursor = {link = "Cursor"},
TermCursorNC = {link = "Cursor"},
CursorColumn = {fg = "#E3E3E3", bg = "#3B3B3B"},
CursorLine = {link = "CursorColumn"},
CursorLineNr = {fg = "#B3B3B3"},
CursorLineFold = {link = "CursorLineNr"},
CursorLineSign = {link = "CursorLineNr"},
ModeMsg = {link = "CursorLineNr"},
Title = {link = "CursorLineNr"},
Debug = {fg = "#FF0000", bg = "#FF0000"},
DiagnosticError = {fg = "#AF8760", bg = "#1C1C1C"},
DiagnosticWarn = {link = "DiagnosticError"},
DiagnosticFloatingHint = {link = "DiagnosticFloatingError"},
DiagnosticFloatingInfo = {link = "DiagnosticFloatingError"},
DiagnosticFloatingOk = {link = "DiagnosticFloatingError"},
DiagnosticFloatingWarn = {link = "DiagnosticFloatingError"},
DiagnosticOk = {fg = "#00D600", bg = "#1C1C1C", bold = true},
DiagnosticSignWarn = {link = "DiagnosticSignError"},
DiagnosticSignOk = {fg = "#00D600", bg = "#1C1C1C"},
DiagnosticSignHint = {link = "DiagnosticSignWarn"},
DiagnosticSignInfo = {link = "DiagnosticSignWarn"},
DiagnosticHint = {link = "DiagnosticWarn"},
DiagnosticInfo = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#00D600", bold = true},
DiffChange = {fg = "#FFD900", bold = true},
DiffDelete = {fg = "#D60000", bold = true},
DiffText = {fg = "#00D600", bold = true},
Directory = {fg = "#FFD900", bg = "#1C1C1C"},
EndOfBuffer = {fg = "#595959"},
NonText = {link = "EndOfBuffer"},
SpecialKey = {link = "EndOfBuffer"},
VertSplit = {link = "EndOfBuffer"},
Whitespace = {link = "EndOfBuffer"},
Winseparator = {link = "EndOfBuffer"},
Error = {fg = "#D60000"},
ErrorMsg = {fg = "#D60000", bg = "#1C1C1C", bold = true},
["@namespace"] = {link = "ErrorMsg"},
FloatTitle = {fg = "#E3E3E3", bg = "#262626", bold = true},
Folded = {bg = "#3B3B3B"},
Function = {fg = "#FF8800"},
["@constructor"] = {link = "Function"},
["@function.builtin"] = {link = "Function"},
Identifier = {fg = "#E3E3E3"},
Delimiter = {link = "Identifier"},
Operator = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#FF0000", bg = "#FF0000"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#B3B3B3"},
DiagnosticSignError = {link = "LineNr"},
LineNrAbove = {fg = "#595959"},
LineNrBelow = {link = "LineNrAbove"},
LspSignatureActiveParameter = {bold = true, underline = true},
MatchParen = {bg = "#3B3B3B"},
MoreMsg = {link = "ModeMsg"},
MsgArea = {link = "ModeMsg"},
MsgSeparator = {link = "ModeMsg"},
Question = {link = "ModeMsg"},
QuickFixLine = {link = "ModeMsg"},
NormalFloat = {fg = "#E3E3E3", bg = "#262626"},
DiagnosticFloatingError = {link = "NormalFloat"},
FloatBorder = {link = "NormalFloat"},
Number = {fg = "#AED6D6"},
Boolean = {link = "Number"},
Float = {link = "Number"},
["@boolean"] = {link = "Number"},
["@float"] = {link = "Number"},
["@number"] = {link = "Number"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#E3E3E3", bg = "#3B3B3B"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {fg = "#3B3B3B", bg = "#3B3B3B"},
PmenuSel = {fg = "#3B3B3B", bg = "#E3E3E3"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
WildMenu = {link = "PmenuSel"},
PmenuThumb = {fg = "#595959", bg = "#595959"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
Tag = {link = "PreProc"},
["@constant.macro"] = {link = "PreProc"},
SignColumn = {fg = "#B3B3B3"},
SpellBad = {undercurl = true},
SpellCap = {link = "SpellBad"},
SpellLocal = {link = "SpellBad"},
SpellRare = {link = "SpellBad"},
Statement = {fg = "#FFD900"},
StatusLine = {fg = "#B3B3B3", bg = "#1C1C1C"},
StatusLineNC = {link = "StatusLine"},
StorageClass = {fg = "#D68800"},
Structure = {link = "StorageClass"},
Typedef = {link = "StorageClass"},
String = {fg = "#88D760"},
Substitute = {fg = "#262626", bg = "#AF8760", bold = true},
TabLine = {fg = "#B3B3B3", bg = "#262626"},
TabLineFill = {link = "TabLine"},
WinBar = {link = "TabLineSel"},
WinBarNC = {link = "TabLineSel"},
Todo = {fg = "#FFD900", bold = true},
Type = {fg = "#FFD900"},
Special = {link = "Type"},
["@type"] = {link = "Type"},
Underlined = {underline = true},
Visual = {bg = "#3B3B3B"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#FFD900", bg = "#1C1C1C", bold = true},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='gmorales_nvim'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
